services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_seguro_root
      MYSQL_DATABASE: campus_event
      MYSQL_USER: campus_user
      MYSQL_PASSWORD: password_seguro_produccion
    ports:
      # Expuesto localmente solo para debugging si es necesario
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password

  nlp:
    build:
      context: ../../nlp_service # El contexto es la carpeta nlp_service (dos niveles arriba si se corre desde server/deploy/)
      dockerfile: Dockerfile
    container_name: nlp_api
    restart: always
    # NO exponemos puertos al host (EC2) para que Flutter/Internet no pueda acceder directo a la IA.
    # Solo Node.js podrá comunicarse con él internamente en el puerto 8000.
    volumes:
      - nlp_models:/app/models_cache
    networks:
      - app_network
    # IMPORTANTE para t3.small: Limitar recursos si es necesario
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G

  api:
    build:
      context: .. # El contexto es la raíz del proyecto Node.js (server/)
      dockerfile: deploy/Dockerfile
    container_name: node_api
    restart: always
    ports:
      # Flutter consumirá la IP elástica a través del puerto 80.
      - "80:3000" 
    environment:
      # Conexión interna dentro de la red de Docker
      DATABASE_URL: "mysql://campus_user:password_seguro_produccion@db:3306/campus_event"
      NLP_SERVICE_URL: "http://nlp:8000"
      JWT_SECRET: "cambia_este_secreto_por_algo_seguro_para_aws"
      UPLOAD_DIR: "uploads/materiales"
      PORT: 3000
    depends_on:
      - db
      - nlp
    volumes:
      - uploads_data:/app/uploads
    command: /bin/sh -c "npx prisma db push --accept-data-loss && node prisma/seed.js && npm start"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysqldata: # Volumen para persistir los datos de MySQL
  uploads_data: # Volumen para persistir PDFs y PPTXs
  nlp_models: # Volumen para persistir modelos de IA y base vectorial FAISS

